import PageWrapper from '@/components/General/PageWrapper';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Login | Mock Test</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
        <div>
          <h1>
            Create <span>T3</span> App
          </h1>

          <div>
            <h3>This stack uses:</h3>
            <ul>
              <li>
                <a href="https://nextjs.org" target="_blank" rel="noreferrer">
                  Next.js
                </a>
              </li>
              <li>
                <a
                  href="https://typescriptlang.org"
                  target="_blank"
                  rel="noreferrer"
                >
                  TypeScript
                </a>
              </li>
            </ul>
          </div>
        </div>
      </PageWrapper>
    </>
  );
};

export default Home;
